name: "SBT build"
description: "Set up SBT, and build the project"

inputs:
  java_version:
    description: "The Java version to use to compile. Default: 8"
    required: false
    default: "8"
  resolvers:
    description: |
      SBT resolvers to configure.
      Expected format:
      resolvers ++= Seq(
        "nameA" at "urlA",
        "nameB" at "urlB",
        "nameC" at "urlC"
      )
    required: true
  build_args:
    description: "Args for SBT tool. Default: clean; compile; +test"
    required: false
    default: "clean; compile; +test"

runs:
  using: "composite"

  steps:
    - name: Setup JDK
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: temurin
        java-version: "${{ inputs.java_version }}"
        cache: sbt

    - name: Setup SBT
      uses: sbt/setup-sbt@2e222825582620cc38d2a54e674f3c01b7c14f5d # v1.1.24

    - name: Configure Resolvers
      shell: bash
      env:
        RESOLVERS: ${{ inputs.resolvers }}
      run: |
        mkdir -p "$HOME/.sbt/1.0"
        printf '%s\n' "$RESOLVERS" > "$HOME/.sbt/1.0/resolvers.sbt"

    - name: Run SBT
      shell: bash
      env:
        BUILD_ARGS: ${{ inputs.build_args }}
      run: sbt -v -Dfile.encoding=UTF8 "$BUILD_ARGS" < /dev/null
