name: Build snapshot version and upload to Gradle Central

on:
  workflow_call:
    inputs:
      project_name:
        description: "Name in <organisation>/<project_name> format. Prevents forks to run the job"
        required: true
        type: string
      java_version:
        description: "The Java version to use to compile. Default: 17"
        required: false
        type: string
        default: "17"
      fetch_all_commits:
        description: "Whether to fetch all commits. Default: false"
        required: false
        type: boolean
        default: false
      snapshot_deploy_args:
        description: "The snapshot args for gradle tool. Default: build publishToCentral -x test -x funcTest"
        required: false
        type: string
        default: "build publishToCentral -x test -x funcTest"

    secrets:
      SONATYPE_USERNAME:
        required: true
      SONATYPE_PASSWORD:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  snapshot:
    if: github.repository == inputs.project_name
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: ${{ inputs.fetch_all_commits == true && '0' || '1' }}
          persist-credentials: false

      - name: Set up JDK '${{ inputs.java_version }}'
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          java-version: "${{ inputs.java_version }}"
          distribution: "temurin"
          cache: gradle
          server-id: central-publisher # we use this in our pom.xml
          server-username: MAVEN_USERNAME # env var name for username
          server-password: MAVEN_PASSWORD # env var name for password

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          gradle-version: "wrapper"

      - name: Extract Project version
        id: project-version
        run: echo "version=$(awk -F "=" 'BEGIN{ORS=""} /version|currentVersion/{print $NF}' gradle.properties)" >> "$GITHUB_OUTPUT"

      - name: Build with Gradle
        if: ${{ endsWith(steps.project-version.outputs.version, '-SNAPSHOT') }}
        shell: bash
        env:
          INPUTS_SNAPSHOT_DEPLOY_ARGS: ${{ inputs.snapshot_deploy_args }}
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          # shellcheck disable=SC2086
          ./gradlew ${INPUTS_SNAPSHOT_DEPLOY_ARGS}
