# This is not meant to be copied and is only for this repository.
name: Update README table of contents
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - README.md

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Allows pushing commits.

    steps:
    - name: Check out repo
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        persist-credentials: false

    - name: Configure Git User
      run: |
        # This sets the name and email for the commits
        git config --global user.name "github-actions[bot]"
        # official github action email
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Update TOC
      run: npx --yes doctoc README.md

    - name: Commit and push if README changed
      run: |-
        git diff
        # Construct the authenticated URL
        # format: https://<token>@github.com/<owner>/<repo>.git
        REMOTE="https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
        git diff --quiet || (git add README.md && git commit -m "Updated README ToC" && git push "${REMOTE}")
      env:
        # Use the standard GITHUB_TOKEN or a Custom PAT if pushing to other repos
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
